# version: '3.8'

# services:
#   web:
#     build: .
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#     volumes:
#       - ./app:/app/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db

#   db:
#     image: postgres:13-alpine
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase

# volumes:
#   postgres_data:

services:
  web:
    build: .
    #command: /bin/sh -c "sleep 10 && python /app/app/create_tables.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    command: /bin/sh -c "sleep 10 && PYTHONPATH=/app python /app/app/create_tables.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
   
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

volumes:
  postgres_data:
